# This file was generated by GoReleaser. DO NOT EDIT.
cask "datadog_import" do
  desc "Cli to convert Dynatrace synthetics to Datadog synthetics"
  homepage "https://github.com/abruneau/datadog_import"
  version "1.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datadog_import"

  on_macos do
    on_intel do
      url "https://github.com/abruneau/datadog_import/releases/download/1.4.1/datadog_import_Darwin_x86_64.tar.gz"
      sha256 "55fe6b48e12666dbf41a48564aea6fe7fa22ddaae9c06a0d9c153e5e362eaceb"
    end
    on_arm do
      url "https://github.com/abruneau/datadog_import/releases/download/1.4.1/datadog_import_Darwin_arm64.tar.gz"
      sha256 "7140145532795dbb0acd52370cc5adf6574626b8fc0f6fd1f7cc06f4412b3224"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abruneau/datadog_import/releases/download/1.4.1/datadog_import_Linux_x86_64.tar.gz"
      sha256 "9edf13027ceb1235f85b2aad755db22f57320f45ae6d5edbb9c36458a3b56120"
    end
    on_arm do
      url "https://github.com/abruneau/datadog_import/releases/download/1.4.1/datadog_import_Linux_arm64.tar.gz"
      sha256 "fea09fdc055a8ce389b0ee42c87e725da67567ff371cfa26d6b62dd9dbd2831c"
    end
  end

  conflicts_with formula: [
      "datadog_import",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/datadog_import"]
    end
  end

  # No zap stanza required
end
