# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogImport < Formula
  desc "Cli to convert Dynatrace synthetics to Datadog synthetics"
  homepage "https://github.com/abruneau/datadog_import"
  version "1.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/abruneau/datadog_import/releases/download/1.3.0/datadog_import_Darwin_x86_64.tar.gz"
      sha256 "bd8a0c70a37c33ba6430eaf6508f044e4db15b7a71c7b2a7e4ccf16c64c51a15"

      def install
        bin.install "datadog_import"
      end
    end
    on_arm do
      url "https://github.com/abruneau/datadog_import/releases/download/1.3.0/datadog_import_Darwin_arm64.tar.gz"
      sha256 "b46f957093b4f9d2a11168c5b13db905ed57d65d7c127987c4877bb1c173f334"

      def install
        bin.install "datadog_import"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abruneau/datadog_import/releases/download/1.3.0/datadog_import_Linux_x86_64.tar.gz"
        sha256 "92a37f7c73817a15336316439f297b88c92908e69612150a2bc7d16aea719a30"

        def install
          bin.install "datadog_import"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abruneau/datadog_import/releases/download/1.3.0/datadog_import_Linux_arm64.tar.gz"
        sha256 "62d5fb7386685ba310dd1c12016440752b679813b1b5351d541265bca8cd629e"

        def install
          bin.install "datadog_import"
        end
      end
    end
  end
end
