# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogImport < Formula
  desc "Cli to convert Dynatrace synthetics to Datadog synthetics"
  homepage "https://github.com/abruneau/datadog_import"
  version "1.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/abruneau/datadog_import/releases/download/1.3.1/datadog_import_Darwin_x86_64.tar.gz"
      sha256 "aaebd958b4c0b12ee61a4c1eadae108e59a5bd247dd7079b0eeade5820453cd1"

      def install
        bin.install "datadog_import"
      end
    end
    on_arm do
      url "https://github.com/abruneau/datadog_import/releases/download/1.3.1/datadog_import_Darwin_arm64.tar.gz"
      sha256 "caeb8d23e48f95d1e27fb1d62b246549e3d10117184afbe73caf5171d89a0fbb"

      def install
        bin.install "datadog_import"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abruneau/datadog_import/releases/download/1.3.1/datadog_import_Linux_x86_64.tar.gz"
        sha256 "c43cf2024b2e95d2c3ce398f98a276ec606003c5d1e156b7c3eaceb80ca0d44c"

        def install
          bin.install "datadog_import"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abruneau/datadog_import/releases/download/1.3.1/datadog_import_Linux_arm64.tar.gz"
        sha256 "a8692eeaf8367e3b4042b2a149e67da8d12397186745381a02ddf40e42c43a7c"

        def install
          bin.install "datadog_import"
        end
      end
    end
  end
end
