# This file was generated by GoReleaser. DO NOT EDIT.
class DdSnmpProfiler < Formula
  desc "dd-snmp-profiler is a CLI to generate SNMP profiles for Datadog"
  homepage ""
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/abruneau/dd-snmp-profiler/releases/download/0.1.2/dd-snmp-profiler_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "8a9dffb6e9f9fb57a9b6f7451d03accdcd5544261e0161f0898421863203612f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/dd-snmp-profiler/releases/download/0.1.2/dd-snmp-profiler_0.1.2_Linux_x86_64.tar.gz"
      sha256 "409a04e449bc94c894c8e62df7cbef42bf148e15bdaaf37e003c2f8187e54a51"
    end
  end

  def install
    bin.install "dd-snmp-profiler"
  end
end
