# This file was generated by GoReleaser. DO NOT EDIT.
class DdSnmpProfiler < Formula
  desc "dd-snmp-profiler is a CLI to generate SNMP profiles for Datadog"
  homepage ""
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/abruneau/dd-snmp-profiler/releases/download/0.1.1/dd-snmp-profiler_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "71f65bc34cbb6a1cc25ff01e8bdc5f01789d1a678648659c18aaf61838bd2601"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/dd-snmp-profiler/releases/download/0.1.1/dd-snmp-profiler_0.1.1_Linux_x86_64.tar.gz"
      sha256 "ab8c1722e758d0fa586bc3ec14e707a789f50859bf65308e6b42d86657793e2b"
    end
  end

  def install
    bin.install "dd-snmp-profiler"
  end
end
