# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DynatraceToDatadog < Formula
  desc "Cli to convert Dynatrace synthetics to Datadog synthetics"
  homepage "https://github.com/abruneau/dynatrace_to_datadog"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/0.0.1/dynatrace_to_datadog_Darwin_x86_64.tar.gz"
      sha256 "0842053cca0c0aad5299c27c5576e078a17d13acfedc77d2685ad383d2d47224"

      def install
        bin.install "dynatrace_to_datadog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/0.0.1/dynatrace_to_datadog_Darwin_arm64.tar.gz"
      sha256 "6e4547cb50587904bca853b2f559e26b6f6ec500d93325d4cc13692451e8dd85"

      def install
        bin.install "dynatrace_to_datadog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/0.0.1/dynatrace_to_datadog_Linux_x86_64.tar.gz"
      sha256 "66f63aff05d383a1c000c4776c2c6b98de546d3375ed72dc744aa3c1b3c8ca64"

      def install
        bin.install "dynatrace_to_datadog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/0.0.1/dynatrace_to_datadog_Linux_arm64.tar.gz"
      sha256 "a4e13379cea8d81e89268435d8aa54439f9c5b1a66391255be182bd120e1c536"

      def install
        bin.install "dynatrace_to_datadog"
      end
    end
  end
end
