# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DynatraceToDatadog < Formula
  desc "Cli to convert Dynatrace synthetics to Datadog synthetics"
  homepage "https://github.com/abruneau/dynatrace_to_datadog"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/1.1.0/dynatrace_to_datadog_Darwin_x86_64.tar.gz"
      sha256 "a60ef995f1249c35ce8f4ba2a4382804743cba9124f83a14f67d07b9bf9e3d10"

      def install
        bin.install "dynatrace_to_datadog"
      end
    end
    on_arm do
      url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/1.1.0/dynatrace_to_datadog_Darwin_arm64.tar.gz"
      sha256 "aab3f9568aa43b0b825023036da687925c6e417a2f97ba6f1becbb6f0fcd6c65"

      def install
        bin.install "dynatrace_to_datadog"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/1.1.0/dynatrace_to_datadog_Linux_x86_64.tar.gz"
        sha256 "ceb7c7800743dc4e259ea0ea73e5288798ede64a9dc825938db641389ed77a28"

        def install
          bin.install "dynatrace_to_datadog"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abruneau/dynatrace_to_datadog/releases/download/1.1.0/dynatrace_to_datadog_Linux_arm64.tar.gz"
        sha256 "bff2a1aebd87c07909eac0b13b453fb9a4312741a27ff4fc181f27af00922454"

        def install
          bin.install "dynatrace_to_datadog"
        end
      end
    end
  end
end
