# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaToDatadog < Formula
  desc "Cli to convert Grafana dashboards to Datadog dashboards"
  homepage "https://github.com/abruneau/grafana_to_datadog"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Darwin_x86_64.tar.gz"
      sha256 "1aa5322f1632d867263e68eed7a8cfdb4e40409d1551c0fbd4ede04a63d63e80"

      def install
        bin.install "grafana_to_datadog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Darwin_arm64.tar.gz"
      sha256 "c769437699644dc3dcea680d4ec1acb6eb4101d8b00570b89495c516a62b7a6d"

      def install
        bin.install "grafana_to_datadog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Linux_arm64.tar.gz"
      sha256 "7736b6e36e5eacf59372ca1f6701be986374261f592cd4aef72d47969af85888"

      def install
        bin.install "grafana_to_datadog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Linux_x86_64.tar.gz"
      sha256 "c2ebb64e216b919c502b4931408ff65e5eb2532de495bd4f61ad7d55787b2f40"

      def install
        bin.install "grafana_to_datadog"
      end
    end
  end
end
