# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaToDatadog < Formula
  desc "Cli to convert Grafana dashboards to Datadog dashboards"
  homepage "https://github.com/abruneau/grafana_to_datadog"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/2.3.0/grafana_to_datadog_Darwin_arm64.tar.gz"
      sha256 "9b20def3459c768aac7b324740cc2f33299268dd6b1530240659210825f6e86c"

      def install
        bin.install "grafana_to_datadog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/2.3.0/grafana_to_datadog_Darwin_x86_64.tar.gz"
      sha256 "5a58e4ec8b641b2751cdea293ff9f0b7961690c80954c7fee2da1a0eb107a999"

      def install
        bin.install "grafana_to_datadog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/2.3.0/grafana_to_datadog_Linux_arm64.tar.gz"
      sha256 "7167ea9b6a15e99bf70bc71e721d85e1c4db33cd8ccac25c9a9a2d82e44ecba1"

      def install
        bin.install "grafana_to_datadog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/2.3.0/grafana_to_datadog_Linux_x86_64.tar.gz"
      sha256 "95103b5b58fed951636dacdc3625fe20a34e0eee54bd57d370dea396ff41355d"

      def install
        bin.install "grafana_to_datadog"
      end
    end
  end
end
