# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaToDatadog < Formula
  desc "Cli to convert Grafana dashboards to Datadog dashboards"
  homepage "https://github.com/abruneau/grafana_to_datadog"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Darwin_arm64.tar.gz"
      sha256 "762b4eef96274c25e9c531155f23a9acb902190b96c26173ef290c9e11ec2beb"

      def install
        bin.install "grafana_to_datadog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Darwin_x86_64.tar.gz"
      sha256 "441bbccccb9035b2f107d08f7855fa4874b62ae9e6a14f9ef9810f79fff9c933"

      def install
        bin.install "grafana_to_datadog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Linux_arm64.tar.gz"
      sha256 "38e6d52da4a615e5d60f085a8205b1cd4708e5a1ade2d5756483a8e38a1dc87d"

      def install
        bin.install "grafana_to_datadog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abruneau/grafana_to_datadog/releases/download/0.2.0/grafana_to_datadog_Linux_x86_64.tar.gz"
      sha256 "2881599125f9277a241b1c21ab27ad2782d5b7444c65c44c530d016fd6f0a94d"

      def install
        bin.install "grafana_to_datadog"
      end
    end
  end
end
